[package]
name = "ldir-bench"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
ldir-core = { workspace = true }
ldir-md = { workspace = true }
ldir-tex = { workspace = true }
ldir-pdf = { workspace = true }
ldir-ir = { workspace = true }
ldir-test-helpers = { workspace = true }
criterion = { workspace = true }
ldir-otelkit = { workspace = true }
tracing = { workspace = true }

[[bench]]
name = "compile"
harness = false

[[bench]]
name = "layout"
harness = false

[[bench]]
name = "pdf"
harness = false
