[package]
name = "ldc"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "LDIR compiler CLI: compile documents to PDF and other formats"

[dependencies]
ldir-core = { workspace = true }
ldir-ir = { workspace = true }
ldir-tex = { workspace = true }
ldir-md = { workspace = true }
ldir-pdf = { workspace = true }
ldir-html = { path = "../ldir-html" }
ldir-epub = { path = "../ldir-epub" }
ldir-txt = { path = "../ldir-txt" }
ldir-docx = { path = "../ldir-docx" }
ldir-typst = { path = "../ldir-typst" }
ldir-html-reader = { path = "../ldir-html-reader" }
ldir-adoc = { path = "../ldir-adoc" }
ldir-org = { path = "../ldir-org" }
ldir-docx-reader = { path = "../ldir-docx-reader" }
anyhow = { workspace = true }
clap = { version = "4", features = ["derive"] }
ttf-parser = { workspace = true }
fontdb = { workspace = true }
