[package]
name = "ldc"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "LDIR compiler CLI: compile documents to PDF and other formats"
repository.workspace = true
readme = "README.md"
keywords = ["compiler", "cli", "document", "typesetting", "pdf"]
categories = ["compilers", "command-line-utilities"]

[dependencies]
ldir-core = { workspace = true }
ldir-ir = { workspace = true }
ldir-tex = { workspace = true }
ldir-md = { workspace = true }
ldir-pdf = { workspace = true }
ldir-html = { workspace = true }
ldir-epub = { workspace = true }
ldir-txt = { workspace = true }
ldir-docx = { workspace = true }
ldir-typst = { workspace = true }
ldir-html-reader = { workspace = true }
ldir-adoc = { workspace = true }
ldir-org = { workspace = true }
ldir-docx-reader = { workspace = true }
anyhow = { workspace = true }
clap = { version = "4", features = ["derive"] }
ttf-parser = { workspace = true }
fontdb = { workspace = true }
